name: First workflow 1
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
          echo "this is first greeting"
          echo "this is second greeting"
      - name: print bye
        run: echo "this is bye bye"
      - name: Get code            
        uses: actions/checkout@v4
